### ISSUE TITLE
Support MacBook with M1 chip

### ISSUE THREAD

**Issue by Hongbo-Miao** [rticommunity/rticonnextdds-connector-py#141] opened 2022-10-12 21:52 UTC
As more and more engineers upgrade to MacBook with M1 chip today.
It would be support MacBook with M1 chip, thanks! 😃

Right now on a MacBook with M1 chip, `import rticonnextdds_connector as rti` will give the error

```shell
Traceback (most recent call last):
  File "/my_app/main.py", line 10, in <module>
    import writer
  File "/my_app/writer.py", line 2, in <module>
    import rticonnextdds_connector as rti
  File "/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds_connector/__init__.py", line 9, in <module>
    from .rticonnextdds_connector import *
  File "/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds_connector/rticonnextdds_connector.py", line 372, in <module>
    connector_binding = _ConnectorBinding() # pylint: disable=invalid-name
  File "/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds_connector/rticonnextdds_connector.py", line 170, in __init__
    self.library = ctypes.CDLL(os.path.join(path, libname), ctypes.RTLD_GLOBAL)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds_connector/../rticonnextdds-connector/lib/osx-x64/librtiddsconnector.dylib, 0x000A): tried: '/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds_connector/../rticonnextdds-connector/lib/osx-x64/librtiddsconnector.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/opt/homebrew/Caskroom/miniconda/base/envs/my_env/lib/python3.8/site-packages/rticonnextdds-connector/lib/osx-x64/librtiddsconnector.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

Might be similar/related to

- https://github.com/rticommunity/rticonnextdds-connector-go/issues/47
- https://github.com/rticommunity/rticonnextdds-connector-go/issues/48

**Comment by samuelraeburn** [comment] 2022-10-13 07:35
Hi!
As you have seen, right now it isn't supported. I have tracked your interest in our internal issue database for support for this.

Note, that the RTI Connext Python API is supported on M1 chips, maybe you could use that instead? If not, I would be interested in hearing why not. More info on the Python API here: https://community.rti.com/static/documentation/connext-dds/7.0.0/doc/api/connext_dds/api_python/index.html

**Comment by Hongbo-Miao** [comment] 2022-10-14 17:50
Thanks @samuelraeburn !

What is the difference between these two? Isn't `rticonnextdds_connector` the Python API?

- `rticonnextdds_connector` I used: https://community.rti.com/static/documentation/connector/current/api/python/getting_started.html
- RTI Connext Python API: https://community.rti.com/static/documentation/connext-dds/7.0.0/doc/api/connext_dds/api_python/index.html

Regarding the RTI Connext Python API, I tried and met antoher error. I posted at https://github.com/rticommunity/rticonnextdds-connector-py/issues/142

**Comment by samuelraeburn** [comment] 2022-10-17 08:22
Hi @Hongbo-Miao 

They are two separate products. Connector for Python provides a much smaller subset of the Connext DDS API in comparison to the Python API.

From the [release notes](https://community.rti.com/static/documentation/connector/current/api/python/intro.html):

> RTI Connector is a family of simplified APIs for publishing and subscribing to the Connext DDS Databus in programming languages such as Python and JavaScript. (RTI also offers a more comprehensive [Python API](https://github.com/rticommunity/connextdds-py), which is experimental.)

I transferred your other issue about installing the Python API into the correct github repo.

**Closed by samuelraeburn** 2022-10-17 08:22 UTC

**Comment by Hongbo-Miao** [comment] 2022-10-18 21:41
Hi @samuelraeburn how many libraries currently for Python? Only two, right? Or three?

1. RTI Connext Python API `connextdds-py` (Currently does not support M1 MacBook):
   - https://community.rti.com/static/documentation/connext-dds/7.0.0/doc/api/connext_dds/api_python/index.html
   - https://github.com/rticommunity/connextdds-py
2. RTI Connector for Python `rticonnextdds_connector` (subset of `connextdds-py`, supporting M1 MacBook)
   - https://community.rti.com/static/documentation/connector/current/api/python/getting_started.html
   - https://github.com/rticommunity/rticonnextdds-connector-py
 
But the one I currently have issue is importing as `import rticonnextdds_connector as rti`, isn't the second one?

Would you mind listing all solutions and links, and which one support M1, which one is subset? I am quite confused right now. Thanks!

**Comment by samuelraeburn** [comment] 2022-10-21 06:16
Hi @Hongbo-Miao I saw in the connextdds-py repo that you managed to get it working.

Your understanding of the different Python APIs is a little wrong. We have:

* Connector
     * Connector is a group of APIs (predominantly for scripting languages) that provide a small subset of the DDS API. They are missing large parts of functionality that many users require (e.g., they only support Dynamic Data, not compiled types).
     * Currently the most used Connectors are Connector for Python (this repository) and [Connector for JavaScript](https://github.com/rticommunity/rticonnextdds-connector-js)
* Connext DDS Python  
     * More akin to a full DDS API, supporting the majority of features that are supported in other language bindings (crucially, supporting compiled types)

With the introduction of the [Connext DDS Python API](https://github.com/rticommunity/connextdds-py/) (a separate product to Connector for Python), the Connector for Python API will likely be deprecated in the future. We recommend users to use the Connext DDS Python API, since it is much more complete.

**Comment by grahonan** [comment] 2022-10-21 22:27
Revisiting this, you can run Connector on ARM-based Macbooks (e.g. M1 processor), but you'll have to do so with macOS's Rosetta emulation. It appears that you have to invoke python with the "arch" command in macOS to get Rosetta to kick in:

```
{dsuser@macm101:23} arch -x86_64 python examples/python/simple/reader.py
Waiting for publications...
Waiting for data...
Received x: 1 y: 2 size: 30.0 color: 'BLUE'
Received x: 2 y: 4 size: 30.0 color: 'BLUE'
```

This should get you around the "incompatible architecture" errors based on my testing.

**Comment by Hongbo-Miao** [comment] 2022-10-21 22:48
Thanks @grahonan ! However, still no luck. Here are the experiments I did:

## Open terminal iTerm directly:

I even reinstalled rosetta.

```
➜ softwareupdate --install-rosetta

I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
Type A and press return to agree: A
2022-10-21 15:46:11.753 softwareupdate[92287:12869638] Package Authoring Error: 012-40509: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
Install of Rosetta 2 finished successfully

➜ arch -x86_64 python examples/python/simple/reader.py
arch: posix_spawnp: python: Bad CPU type in executable

➜ arch
arm64

➜ uname -m
arm64

➜ uname -p
arm
```

## Open terminal iTerm in Rosetta mode:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/3375461/197299802-cf210059-a442-4af1-9d5d-f57716571930.png">

Then I got

```
➜ arch -x86_64 python examples/python/simple/reader.py
arch: posix_spawnp: python: Bad CPU type in executable

rticonnextdds-connector-py on  master via 🅒 base
➜ arch
i386

rticonnextdds-connector-py on  master via 🅒 base
➜ uname -m
x86_64

rticonnextdds-connector-py on  master via 🅒 base
➜ uname -p
i386
```

**Comment by Hongbo-Miao** [comment] 2022-10-21 23:18
I tried to comment out everything in the `~/.zshrc`. And use Terminal instead of iTerm from macOS (zsh):

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3375461/197303997-4ff429b8-5778-45ef-888c-0857e6de4faa.png">

Still got same error

```
> arch -x86_64 python3 examples/python/simple/reader.py
arch: posix_spawnp: python3: Bad CPU type in executable
```

**Comment by grahonan** [comment] 2022-10-21 23:35
I think the problem is related to the miniconda distribution of Python unfortunately:

```
(base) Graysons-MBP:~ grayson$ which python3
/usr/bin/python3
(base) Graysons-MBP:~ grayson$ arch -x86_64 python3
Python 3.8.9 (default, May 17 2022, 12:55:41)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
(base) Graysons-MBP:~ grayson$ export PATH=/Users/grayson/opt/miniconda3/bin:/Users/grayson/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
(base) Graysons-MBP:~ grayson$ which python3
/Users/grayson/opt/miniconda3/bin/python3
(base) Graysons-MBP:~ grayson$ arch -x86_64 python3
arch: posix_spawnp: python3: Bad CPU type in executable
```

**Comment by grahonan** [comment] 2022-10-21 23:43
The problem is that miniconda Python is not a universal binary, but the Python in /usr/bin (provided by Apple) is built as universal:

```
(base) Graysons-MBP:~ grayson$ file /Users/grayson/opt/miniconda3/bin/python3
/Users/grayson/opt/miniconda3/bin/python3: Mach-O 64-bit executable arm64

(base) Graysons-MBP:~ grayson$ file /usr/bin/python3
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e
- Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

**Comment by Hongbo-Miao** [comment] 2022-10-22 00:03
Thank you soooo much, @grahonan ! That is the issue!

As I do need use `conda`. Here is my final solution:

Add this code in `.zshrc`

```sh
# Create x86 conda environment
create_x86_conda_environment () {
 CONDA_SUBDIR=osx-64 conda create -n $@
 conda activate $1
}

# Create ARM conda environment
create_ARM_conda_environment () {
 CONDA_SUBDIR=osx-arm64 conda create -n $@
 conda activate $1
}
```

Then I can run

```sh
create_x86_conda_environment py38_x86 python=3.8
conda activate py38_x86
cd rticonnextdds-connector-py
python examples/python/simple/reader.py
```
